- id: '1644416089090'
  alias: Ny automasjon
  description: ''
  use_blueprint:
    path: homeassistant/dimmer_switch.yaml
    input:
      dimmer: sensor.do_fjernkontroll_action
      light: light.dogruppe
- id: '162342346215'
  alias: eirik test volum
  description: ''
  use_blueprint:
    path: homeassistant/symfonisk_rotary.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.eirik_kontor_volum_action
      helper_last_controller_event: input_text.symfonisk_eirik_kontor
      helper_debounce_delay: 1
- id: '6152515215515'
  alias: Eirik Kontor Volum
  description: ''
  use_blueprint:
    path: homeassistant/media_hook.yaml
    input:
      controller_device: 44c1c48adb0a27c5d0f659bf8fbb8ea1
      controller_entity: sensor.eirik_kontor_volum_action
      controller_model: IKEA E1744 SYMFONISK Rotary Remote
      media_player: media_player.eirik_kontor
      volume_steps_short: 1
      volume_steps_long: 50
- id: '1644417233881'
  alias: Ny automasjon
  description: ''
  use_blueprint:
    path: homeassistant/dimmer_switch.yaml
    input:
      dimmer: sensor.kjokken_veggbryter_action
      light: light.kjokkengruppe
- id: '1645720712015'
  alias: Ny automasjon
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 6ee10cc8f99cda4aaaad789f86c508e1
    type: action
    subtype: 'on'
    discovery_id: 0xcc86ecfffe9891e0 action_on
  condition: []
  action:
  - type: turn_on
    device_id: 0e6c972a7ae5b514d9cf42cb4cc721c5
    entity_id: light.kjokkengruppe_2
    domain: light
    brightness_pct: 100
  mode: single
- id: '1645721254603'
  alias: kjokken volum
  description: ''
  use_blueprint:
    path: homeassistant/symfonisk_rotary.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.kjokken_lyd_action
      helper_last_controller_event: input_text.kjokken_lyd
      helper_debounce_delay: 1
- id: '6152515215555'
  alias: kjokken lyd  Volum
  description: ''
  use_blueprint:
    path: homeassistant/media_hook.yaml
    input:
      controller_device: 3da2f59bd05ba7dcadf2ece0e00ecc97
      controller_entity: sensor.kjokken_lyd_action
      controller_model: IKEA E1744 SYMFONISK Rotary Remote
      volume_steps_short: 1
      volume_steps_long: 50
      media_player: media_player.kjokken_2
- id: '1653774897587'
  alias: alva dør
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 79beca0e8bc377f4e885a339a2ea0262
    entity_id: binary_sensor.alva_dorsensor_contact
    domain: binary_sensor
  condition: []
  action:
  - service: notify.eirikz_telegram
    data:
      message: alva dør åpnet
  mode: single
- id: '1661072919141'
  alias: Skru på varmepumpe soverom
  description: ''
  trigger:
  - platform: time
    at: '19:00:00'
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 22
      hvac_mode: cool
    target:
      entity_id: climate.varmepumpe_soverom
  mode: single
- id: '1661073025143'
  alias: Skru av varmepumpe soverom
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.varmepumpe_soverom
  mode: single
