homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 60.108695
  longitude: 11.368363
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 220
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  whitelist_external_dirs:
    - /tmp
#  customize: !include customize.yaml
  packages: !include_dir_named packages

##Define External\Internal URI##
  external_url: !secret baseurl
  internal_url: !secret baseurl


##Eirikz added MFA###
  auth_mfa_modules:
    - type: totp

  customize: !include customize.yaml

system_health:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
 http:

updater:
  include_used_components: true

python_script:

conversation:

history:

logbook:

map:

sun:

### Input booleans ###

input_boolean: 
  dummy_fremme:
    name: "Dummy Fremme Input Boolean"
    icon: mdi:sticker-emoji
    initial: on

  dummy_bak:
    name: "Dummy Bak Input Boolean"
    icon: mdi:sticker-emoji
    initial: on


### Input Selects ####

input_select:
   loftlys:
     name: Loftlys
     options:
       - loftheltpa
       - loftheltav
     icon: mdi:lightbulb-on-outline

   eirik_status_dropdown:
     name: Eirik
     options:
       - Hjemme
       - Kom akkurat hjem
       - Dro akkurat ut
       - Ute
       - Bortreist
     initial: Hjemme

   w_status_dropdown:
     name: W
     options:
       - Hjemme
       - Kom akkurat hjem
       - Dro akkurat ut
       - Ute
       - Bortreist
     initial: Hjemme

### Weather ###

weather:

### TTS ###

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    base_url: !secret baseurl_ga
    language: 'no'

### Includes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml


logger:
  default: warn
  logs:
   homeassistant.components.google_assistant.http: critical

 
### Telldus Live ###

tellduslive:
  host: !secret telldusip

### Lights ###

light:

### Wiz Lights ###
  - platform: wiz_light
    name: Eirik Soverom
    host: 192.168.1.159

### Zigbee2mqtt groups ###

  - platform: mqtt
    schema: json
    name: StueGruppe
    command_topic: "zigbee2mqtt/stuegruppe/set"
    state_topic: "zigbee2mqtt/stuegruppe"

    color_temp: true
    brightness: true
    rgb: false

  - platform: mqtt
    schema: json
    name: KjøkkenGruppe
    command_topic: "zigbee2mqtt/kjokkengruppe/set"
    state_topic: "zigbee2mqtt/kjokkengruppe"

    color_temp: true
    brightness: true
    rgb: false


  - platform: mqtt
    schema: json
    name: KjellerGruppe
    command_topic: "zigbee2mqtt/kjellergruppe/set"
    state_topic: "zigbee2mqtt/kjellergruppe"

    color_temp: false
    brightness: true
    rgb: false


  - platform: mqtt
    schema: json
    name: eirikgruppe
    command_topic: "zigbee2mqtt/eirikgruppe/set"
    state_topic: "zigbee2mqtt/eirikgruppe"

    color_temp: false
    brightness: true
    rgb: false

  - platform: mqtt
    schema: json
    name: soveromgruppe
    command_topic: "zigbee2mqtt/soveromgruppe/set"
    state_topic: "zigbee2mqtt/soveromgruppe"

    color_temp: true
    brightness: true
    rgb: false

  - platform: mqtt
    schema: json
    name: utegruppe
    command_topic: "zigbee2mqtt/utegruppe/set"
    state_topic: "zigbee2mqtt/utegruppe"

    color_temp: true
    brightness: true
    rgb: false


### Light Switches ###

  - platform: switch
    name: Stue Gangbord
    entity_id: switch.lys_gangbord

  - platform: switch
    name: dim
    entity_id: switch.dim

  - platform: switch
    name: Stue Stålampe
    entity_id: switch.stalampe

### Light Groups ###

  - platform: group
    name: Alvakjokken
    entities:
      - light.alva_mikro
      - light.alva_komfyr
      - light.alva_benkelys

  - platform: group
    name: Soverom_lys
    entities:
      - light.soverom_hodegavel
      - light.soverom_lampe_w_light
      - light.soverom_w_light
      - light.eirik_soverom

  - platform: group
    name: Stue_lys
    entities:
      - light.stue_stuebord_light
      - light.stue_ganglys_light
      - light.stue_vinduslampe1_light
      - light.stue_vinduslampe2_light
      - light.stue_gulvlampe1_light
      - light.stue_gulvlampe2_light
      - light.stue_gulvlampe3_light
      - light.stue_bikkjelampe_light
      - light.stue_lys_bak_tv_light
      - light.stue_stort_vitrineskap_light
      - light.stue_lite_vitrineskap
      - light.stue_lyst_vitrineskap
      - light.stue_peislys
      - light.stue_mellomgang_light
      - light.stue_yttergang_tak_light
      - light.stue_yttergang_tak_2_light

  - platform: group
    name: Kjokken_lys
    entities:
      - light.kjokken_benkelys_light
      - light.kjokken_vinduslampe_light
      - light.kjokken_bordlampe_light
      - light.kjokken_benke_underlys_light
      - light.kjokken_taklampe_light
      - light.kjokken_ventilator_light


  - platform: group
    name: Kjeller_lys
    entities:
      - light.kjeller_ganglys_light
      - light.kjeller_vaskerom1_light
      - light.kjeller_vaskerom2_light
      - light.kjeller_vaskerom3_light
      - light.kjeller_trappelys_light
      - light.kjeller_fryserom_light
      - light.kjeller_bod_light

  - platform: group
    name: Loft_lys
    entities:
      - light.loft_taklys_1
      - light.loft_taklys_2
      - light.loft_gulvlampe1_light
      - light.loft_gulvlampe2_light
      - light.loft_gulvlampe3_light

  - platform: group
    name: Kontor_eirik_lys
    entities:
      - light.eirik_kontor1_light
      - light.eirik_kontor2_light
      - light.eirik_kontor3_light


  - platform: group
    name: Do_lys
    entities:
      - light.do_hyllelampe_light
      - light.do_taklys_light

  - platform: group
    name: halloween
    entities:
      - light.grin
      - light.smile

### Yeelight ###

yeelight:
  devices:
    192.168.1.81:
      name: "Loft Taklys 1"
      model: color2
    192.168.1.82:
      name: "Loft Taklys 2"
      model: color2
    192.168.1.83:
      name: "Soverom Hodegavel"
      model: strip1

### Switches ###

switch:

### Switch Templates ###

  - platform: template
    switches:
      garasjedor:
        value_template: "{{ is_state('binary_sensor.garasjeport_sensor', 'on') }}"
        turn_on:
          service: cover.open_cover
          data:
            entity_id: cover.garasjeport_cover
        turn_off:
          service: cover.close_cover
          data:
            entity_id: cover.garasjeport_cover
        icon_template: >-
          {% if is_state('cover.garasjeport_cover', 'open') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}


### Circadian Lighting ###

  - platform: circadian_lighting
    name: stue
    lights_brightness:
      - light.stue_lys
    max_brightness: 75
    min_brightness: 1

    lights_ct:
      - light.stue_lys

  - platform: circadian_lighting
    name: peis
    lights_brightness:
      - light.stue_peislys
    max_brightness: 75
    min_brightness: 12

    lights_ct:
      - light.stue_peislys 

  - platform: circadian_lighting
    name: do
    lights_brightness:
      - light.do_taklys_light
      - light.do_hyllelampe_light
    max_brightness: 75
    min_brightness: 15

    lights_ct:
      - light.do_taklys_light
      - light.do_hyllelampe_light



  - platform: circadian_lighting
    name: kjeller
    lights_brightness:
#      - light.kjeller_ganglys_light
#      - light.kjeller_vaskerom1_light
#      - light.kjeller_vaskerom2_light
#      - light.kjeller_vaskerom3_light
#      - light.kjeller_trappelys_light
#      - light.kjeller_fryserom_light
#      - light.kjeller_bod_light
      - light.kjellergruppe
    max_brightness: 75
    min_brightness: 1

  - platform: circadian_lighting
    name: loft
    lights_brightness:
      - light.loft
    max_brightness: 75
    min_brightness: 1

    lights_ct:
      - light.loft_taklys_1
      - light.loft_taklys_2

  - platform: circadian_lighting
    name: kjokken   
    lights_brightness:
      - light.kjokken_lys
    max_brightness: 75
    min_brightness: 1


  - platform: circadian_lighting
    name: kontor
    lights_brightness:
      - light.kontor_eirik_lys
    max_brightness: 75
    min_brightness: 1


zone: !include zones.yaml 

scene: !include scenes.yaml

### Spotify ###

spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_clientsecret

### WebosTV ###

webostv:
  host: 192.168.1.32
  name: StueTV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "14-C9-13-15-1F-BD"
      broadcast_address: 192.168.1.255
      broadcast_port: 9
### Media Player Platform ###

media_player:

### Onkyo ###

  - platform: onkyo
    host: !secret onkyoip
    name: Stueforsterker

### Broadlink devices ###
  - platform: smartir
    name: LoftTV
    unique_id: lofttv
    device_code: 1060
    controller_data: remote.broadlink_loft_remote

  - platform: smartir
    name: LoftForsterker
    unique_id: loftforsterker
    device_code: 1121
    controller_data: remote.broadlink_loft_remote


### WoL ###

wake_on_lan:

### Roborock ###

vacuum:
  - platform: xiaomi_miio
    host: !secret roborockip
    token: !secret vacuum

### Google Calendar ###

google:
  client_id: !secret google_clientid
  client_secret: !secret google_clientsecret

### Circadian Lighting ###

circadian_lighting:
  interval: 600
  transition: 60
  min_colortemp: 2200

### YAML mode for Lovelace ###

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/calendar-card/calendar-card.js
      type: js
    - url: /hacsfiles/light-entity-row/light-entity-row.js
      type: js
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/spotify-card/spotify-card.js
      type: module
    - url: /hacsfiles/seventeen-track-card/seventeen-track-card.js
      type: js
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/surveillance-card/surveillance-card.js
      type: module
    - url: /hacsfiles/travel-time-card/travel-time-card.js
      type: js
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: js 
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
      type: module 
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: js
    - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
      type: js

    - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
      type: module


### Binary sensors ###

binary_sensor:
  - platform: ping
    host: 192.168.1.40
    name: Kakuzu
    count: 3
    scan_interval: 30

  - platform: ping
    host: www.google.com
    name: googleping
    count: 3
    scan_interval: 60

  - platform: mqtt
    name: "fremme"
    state_topic: "cameras/fremme/motion"

  - platform: mqtt
    name: "bak"
    state_topic: "cameras/bak/motion"

  - platform: template
    sensors:
      torketrommel_kjorer:
        friendly_name: "Tørketrommel Kjører"
        delay_on:
          minutes: 10
        delay_off:
          minutes: 3
        value_template: >-
          {{ states('sensor.torketrommel_energy_power')|float > 10 }}

  - platform: template
    sensors:
      lys_timer:
        friendly_name: "Det har gått 30 minutter fra vekking av hus"
        value_template: >-
          {{ as_timestamp(now()) - as_timestamp(states.automation.vekk_huset.attributes.last_triggered) | int > 1800 }}        
        
            



### Template for both basement doors open \ close will trigger lights in basement ###

  - platform: template
    sensors:
      kjeller_apen:
        friendly_name: "Kjellerdører åpne"
        device_class: door
        value_template: >-
          {{ is_state('binary_sensor.kjeller_trappedor', 'on') or
             is_state('binary_sensor.kjeller_garasjedor_contact', 'on') }}


### Notify ###

notify:
  - name: 'Eirikz Telegram'
    platform: telegram
    chat_id: !secret eirikzchatid

  - name: 'W Telegram'
    platform: telegram
    chat_id: !secret wchatid

  - name: 'WE Telegram'
    platform: group
    services:
      - service: eirikz_telegram
      - service: w_telegram 


### MariaDB instead of SQLite ###

recorder:
  db_url: !secret mariadb
### Persons ###

person:

### Telegram Bot ###

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret eirikzchatid
      - !secret wchatid

### Climate ###

climate:
  - platform: climate_ip
    config_file: '/config/custom_components/climate_ip/samsung_2878.yaml'
    ip_address: !secret climateip
    token: !secret climatetoken
    mac: !secret climatemac
    name: 'Varmepumpe Stue'
    poll: True

  - platform: smartir
    name: 'Varmepumpe Loft'
    unique_id: loftpumpe
    device_code: 1260
    controller_data: remote.broadlink_loft_remote
    temperature_sensor: sensor.loft_temperatur_temperature
    humidity_sensor: sensor.loft_fuktighet_humidity


### InfluxDB ###

influxdb:
  host: kakuzu.eirikzlab.local
  port: 8086
  username: !secret influxdbuser
  password: !secret influxdbpass
  ssl: false
  verify_ssl: false


### Image Processing ###

image_processing:
  - platform: doods
    scan_interval: 10000
    url: "http://kakuzu.eirikzlab.local:8011"
    detector: tensorflow
    source:
      - entity_id: camera.fremme
    file_out:
      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    confidence: 40
    labels:
      - person
      - car
      - cat
      - dog
      - bottle
      - cup
      - bowl
      - chair
      - couch

  - platform: doods
    scan_interval: 10000
    url: "http://kakuzu.eirikzlab.local:8011"
    detector: default
    source:
      - entity_id: camera.bak
    file_out:
      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    confidence: 20

  - platform: openalpr_local
    region: eu
    source:
    - entity_id: camera.fremme

### ffmpeg ###

ffmpeg:

### Stream ###

stream:

### LIFE360 ###

life360:
  accounts:
    - username: !secret LIFE360_USERNAME
      password: !secret LIFE360_PASSWORD
  driving_speed: 15
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  warning_threshold: 2
  error_threshold: 3


### MQTT ###

mqtt:
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


### Zigbee2mqtt network map ###

webhook:
 
zigbee2mqtt_networkmap:


### Sonos ####

sonos:
  media_player:
    hosts:
      - !secret sonoskontorip

### Google Cast ###

cast:

### MJPEG camera from Motion ###

camera:
  - platform: generic
    name: Fremme
    stream_source: !secret fremmekamerastream
    still_image_url: !secret fremmekamerastill


  - platform: generic
    name: Bak
    stream_source: !secret bakkamerastream
    still_image_url: !secret bakkamerastill

  - platform: mjpeg
    name: Print
    mjpeg_url: !secret printkamerastill
    still_image_url: !secret printkamerastill


### Siemens HomeConnect ###

home_connect:
  client_id: !secret HC_clientID
  client_secret: !secret HC_clientS

### SmartIR ###

smartir:

### Mobile App ###

mobile_app:

### Tibber power company ###
tibber:
  access_token: !secret tibberat


### Octoprint ###

octoprint:
  host: kakuzu.eirikzlab.local
  port: 5000
  api_key: !secret octoapi
  bed: true
  number_of_tools: 1


### Google Assistant Integration because Nabu Casa sucks###

google_assistant:
  project_id: !secret projectidga
  service_account: !include service.json
  report_state: true
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - fan
    - cover
    - media_player
    - climate
    - vacuum
    - sensor
  entity_config:
    light.alva:
      expose: false
    light.do_lys:
      expose: false
    light.eirikgruppe:
      expose: false
    light.ezkontor:
      expose: false
    light.kjeller_lys:
      expose: false
    light.kjellergruppe:
      expose: false
    light.kjokkengruppe:
      expose: false
    light.kjokken_lys:
      expose: false
    light.kjokken:
      expose: false
    light.loft:
      expose: false
    light.loft_lys:
      expose: false
    light.soverom_lys:
      expose: false
    light.soveromgruppe:
      expose: false
    light.stue:
      expose: false
    light.stue_lys:
      expose: false
    light.ute:
      expose: false
    light.utegruppe:
      expose: false
    switch.circadian_lighting_do:
      expose: false
    switch.circadian_lighting_kjeller:
      expose: false
    switch.circadian_lighting_kjokken:
      expose: false
    switch.circadian_lighting_kontor: 
      expose: false
    switch.circadian_lighting_loft:
      expose: false
    switch.circadian_lighting_peis:
      expose: false
    switch.circadian_lighting_stue:
      expose: false
    switch.vaskemaskin_program_auto30:
      expose: false
    switch.vaskemaskin_program_auto40:
      expose: false
    switch.vaskemaskin_program_auto60:
      expose: false
    switch.vaskemaskin_program_chiffon:
      expose: false
    switch.vaskemaskin_program_cotton:
      expose: false
    switch.vaskemaskin_program_cottoneco:
      expose: false
    switch.vaskemaskin_program_curtains:
      expose: false
    switch.vaskemaskin_program_darkwash:
      expose: false
    switch.vaskemaskin_program_delicatessilk:
      expose: false
    switch.vaskemaskin_program_dessous:
      expose: false
    switch.vaskemaskin_program_easycare:
      expose: false
    switch.vaskemaskin_program_mix:
      expose: false
    switch.vaskemaskin_program_monsoon:
      expose: false
    switch.vaskemaskin_program_outdoor:
      expose: false
    switch.vaskemaskin_program_plushtoy:
      expose: false
    switch.vaskemaskin_program_sensitive:
      expose: false
    switch.vaskemaskin_program_shirtsblouses:
      expose: false
    switch.vaskemaskin_program_sportfitness:
      expose: false
    switch.vaskemaskin_program_towels:
      expose: false
    switch.vaskemaskin_program_waterproof:
      expose: false
    switch.vaskemaskin_program_wool:
      expose: false

### Garbage Collection Custom Component ###

garbage_collection:
  sensors:
  - name: "Restavfall"
    frequency: "odd-weeks"
    collection_days:
    - mon
    expire_after: '12:00'

  - name: "Plast og papir" 
    frequency: "annual"
    date: '01/01'
    include_dates:
    - '2020-11-27'
    - '2020-12-28'


### TPLink Smart plug
tplink:
  discovery: false
  switch:
    - host: !secret tplinkvvb 

### Speedtest ###
speedtestdotnet:
  server_id: 12919
  scan_interval:
    hours: 12


### Microsoft Graph ###
microsoft_graph:
  client_id: !secret mgclientid 
  client_secret: !secret mgclientsecret 
