homeassistant:
  name: Home
  latitude: 60.108695
  longitude: 11.368363
  elevation: 220
  unit_system: metric
  time_zone: Europe/Oslo
  currency: NOK
  allowlist_external_dirs:
    - /tmp
  packages: !include_dir_named packages
#  auth_providers:
#    - type: trusted_networks
#      trusted_networks:
#        - 192.168.1.60/32

##Define External\Internal URI##
  external_url: !secret baseurl
  internal_url: !secret baseurl

##Eirikz added MFA###
  auth_mfa_modules:
    - type: totp

  customize: !include customize.yaml

### Enable system health ###
system_health:

### Enable mobile app (yuck) ###
mobile_app:

### Enable energy dashboards ###
energy:

### Enable blueprints ###
blueprint:

### Enable bluetooth ###
bluetooth:

### Enables the frontend ###
frontend:

### Enables configuration UI ###
config:

### Enables zeroconf ###
zeroconf:

### Enable weather ###
weather:

### Enable python scripts ###
python_script:

### Enable conversation ###
conversation:

### Enable history ###
history:

### Enable logbook ###
logbook:

### Enable the map ###
map:

### Enable sun integration ###
sun:

### WoL ###
wake_on_lan:

### Persons ###
person:

### Webhooks ###
webhook:

### SmartIR ###
smartir:


### MariaDB instead of SQLite (yuck) ###
recorder:
  db_url: !secret mariadb


### Enable influxdb for longterm storage of data ###

#influxdb:
#  api_version: 2
#  ssl: false
#  host: mirai.eirikzlab.local
#  port: 8086
#  token: !secret influxtoken
#  organization: !secret influxorg
#  bucket: eirikz



### Enable utility meter ###
utility_meter:

### Enable powercalc ###
powercalc:


### Includes ###

group: !include groups.yaml
automation: !include automations.yaml
automation mine: !include_dir_merge_list automation/
script: !include scripts.yaml
sensor: !include sensors.yaml
homekit: !include homekit.yaml
zone: !include zones.yaml 
scene: !include scenes.yaml
template: !include template.yaml



### Configure http server ###
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.0/16
    - 172.18.0.0/16
    - 172.20.0.0/16


### Enable logger ###

logger:
  default: warn
  logs:
   homeassistant.components.google_assistant.http: critical


### Input booleans ###
input_boolean: 
  dummy_fremme:
    name: "Dummy Fremme Input Boolean"
    icon: mdi:sticker-emoji
    initial: on

  dummy_bak:
    name: "Dummy Bak Input Boolean"
    icon: mdi:sticker-emoji
    initial: on

  torketrommel:

  vaskemaskin:


### Input datetime ### 
input_datetime:
  torketrommel_start:
    has_date: true
    has_time: true
  vaskemaskin_start:
    has_date: true
    has_time: true    

### Input Text ###
input_text:
  symfonisk_eirik_kontor:
    name: bahhumbug
    initial: text

  kjokken_lyd:
    name: kjokkenlyd
    initial: text


### Input Selects ####
input_select:
   loftlys:
     name: Loftlys
     options:
       - loftheltpa
       - loftheltav
     icon: mdi:lightbulb-on-outline

   eirik_status_dropdown:
     name: Eirik
     options:
       - Hjemme
       - Kom akkurat hjem
       - Dro akkurat ut
       - Ute
       - Bortreist
     initial: Hjemme

   w_status_dropdown:
     name: W
     options:
       - Hjemme
       - Kom akkurat hjem
       - Dro akkurat ut
       - Ute
       - Bortreist
     initial: Hjemme

   w_kontor:
     name: W Kontor Bryter
     options:
       - w_kontor_1
       - w_kontor_2
       - w_kontor_3
       - w_kontor_4
       - w_kontor_5
     initial: w_kontor_1

   vaskemaskin_status:
     name: Vaskemaskin Status
     options:
      - "Av"
      - "Vasker"
     initial: "Av"
     icon: mdi:washing-machine
    
   torketrommel_status:
     name: Tørketrommel Status
     options:
      - "Av"
      - "Tørker"
     initial: "Av"
     icon: mdi:washing-machine


### Enable TTS ###

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    language: 'no'

 
### Telldus Live ###

tellduslive:
  host: !secret telldusip

### Lights ###
mqtt: 
  light:

### Zigbee2mqtt groups ###

    - schema: json
      name: KjellerGruppe
      command_topic: "zigbee2mqtt/kjellergruppe/set"
      state_topic: "zigbee2mqtt/kjellergruppe"

      color_temp: false
      brightness: true
      rgb: false

    - schema: json
      name: soveromgruppe
      command_topic: "zigbee2mqtt/soveromgruppe/set"
      state_topic: "zigbee2mqtt/soveromgruppe"

      color_temp: true
      brightness: true
      rgb: false

    - schema: json
      name: utegruppe
      command_topic: "zigbee2mqtt/utegruppe/set"
      state_topic: "zigbee2mqtt/utegruppe"

      color_temp: true
      brightness: true
      rgb: false

    - schema: json
      name: Kveldsgruppe
      command_topic: "zigbee2mqtt/kvelds_gruppe/set"
      state_topic: "zigbee2mqtt/kvelds_gruppe"

      color_temp: true
      brightness: true
      rgb: false


  sensor:
    - name: "PowerElwiz"
      state_topic: "elwiz/sensor/data/state"
      unit_of_measurement: "kW"
      value_template: "{{ value_json.power }}"

    - name: leaf_battery_level
      state_topic: "leaf/battery/percentage"
      device_class: battery

    - name: leaf_cabintemp
      state_topic: "leaf/climate/cabinTemperatureC"
      device_class: temperature
    
    - name: leaf_climaterunning
      state_topic: "leaf/climate/runningStatus"

    - name: leaf_position_lat
      state_topic: "leaf/location/latitude"

    - name: leaf_position_lon
      state_topic: "leaf/location/longitude"


  button:
    - unique_id: climate_start_leaf
      name: "Leaf start varme"
      command_topic: "leaf/SJNFAAZE1U0111923/command/climate"
      payload_press: "start"

    - unique_id: climate_stop_leaf
      name: "Leaf stopp varme"
      command_topic: "leaf/SJNFAAZE1U0111923/command/climate"
      payload_press: "stop"

    - unique_id: climate_get_leaf       
      name: "Leaf hent varme"
      command_topic: "leaf/SJNFAAZE1U0111923/command/climate"
      payload_press: "update"


### Light Switches ###
light: 

  - platform: switch
    name: Stue Gangbord
    entity_id: switch.lys_gangbord

  - platform: switch
    name: Kjokken Stor Pære
    entity_id: switch.kjokken_stor_paere

### Light Groups ###

  - platform: group
    name: Alvakjokken
    entities:
      - light.alva_mikro
      - light.alva_komfyr
      - light.alva_benkelys

  - platform: group
    name: Soverom_lys
    entities:
      - light.soverom_hodegavel
      - light.eirik_soverom
      - light.soverom_lampe_w
  
  - platform: group
    name: W_kontor_lys_gruppe
    entities:
      - light.w_kontor_liten1
      - light.w_kontor_liten2
      - light.w_kontor_tak
      - light.w_kontor_spiss

  - platform: group
    name: Primær_lys
    entities:
      - light.stue_stuebord
      - light.stue_gul_gulvlampe

  - platform: group
    name: Kjeller_lys
    entities:
      - light.kjeller_ganglys_light
      - light.kjeller_vaskerom1_light
      - light.kjeller_vaskerom2_light
      - light.kjeller_vaskerom3_light
      - light.kjeller_trappelys_light
      - light.kjeller_fryserom_light
      - light.kjeller_bod_light

  - platform: group
    name: Loft_lys
    entities:
      - light.loft_taklys_1
      - light.loft_taklys_2
      - light.loft_gulvlampe1
      - light.loft_gulvlampe2
      - light.loft_gulvlampe3
      - light.loft_trappelys

  - platform: group
    name: Do_lys
    entities:
      - light.do_hyllelampe
      - light.do_taklys

  - platform: group
    name: garasjegruppe
    entities:
      - light.garasjelys1



  - platform: group
    name: kjokkengrp
    entities:
      - light.kjokken_benkelys
      - light.kjokken_hengelampe
      - light.kjokken_taklampe
      - light.kjokken_ventilator
      - light.kjokken_vinduslampe
      - light.kjokkenbenk_under

### Yeelight ###

yeelight:
  devices:
    192.168.1.81:
      name: "Loft Taklys 1"
      model: color2
    192.168.1.82:
      name: "Loft Taklys 2"
      model: color2
    192.168.1.83:
      name: "Soverom Hodegavel"
      model: strip1

### Switches ###

switch:

### Switch Templates ###

  - platform: template
    switches:
      garasjedor:
        value_template: "{{ is_state('binary_sensor.garasjeport_sensor', 'on') }}"
        turn_on:
          service: cover.open_cover
          data:
            entity_id: cover.garasjeport_cover
        turn_off:
          service: cover.close_cover
          data:
            entity_id: cover.garasjeport_cover
        icon_template: >-
          {% if is_state('cover.garasjeport_cover', 'open') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}



media_player:

### Broadlink devices ###
  - platform: smartir
    name: LoftTV
    unique_id: lofttv
    device_code: 1060
    controller_data: remote.broadlink_loft_remote

  - platform: smartir
    name: LoftForsterker
    unique_id: loftforsterker
    device_code: 1121
    controller_data: remote.broadlink_loft_remote





### YAML mode for Lovelace ###

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/calendar-card/calendar-card.js
      type: js
    - url: /hacsfiles/light-entity-row/light-entity-row.js
      type: js
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/spotify-card/spotify-card.js
      type: module
    - url: /hacsfiles/seventeen-track-card/seventeen-track-card.js
      type: js
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/surveillance-card/surveillance-card.js
      type: module
    - url: /hacsfiles/travel-time-card/travel-time-card.js
      type: js
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: js 
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: js
    - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
      type: js
    - type: js
      url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js
    - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
      type: module
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/clock-weather-card/clock-weather-card.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: module
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: module


### Binary sensors ###

binary_sensor:

### Template for both basement doors open \ close will trigger lights in basement ###

  - platform: template
    sensors:
      kjeller_apen:
        friendly_name: "Kjellerdører åpne"
        device_class: door
        value_template: >-
          {{ is_state('binary_sensor.kjeller_trappedor_contact', 'on') or
             is_state('binary_sensor.kjeller_garasjedor_contact', 'on') }}

### Template for if any of the garage doors are open \ triggering lights ###

  - platform: template
    sensors:
      garasje_apen:
        friendly_name: "Garasjen er entret"
        device_class: door
        value_template: >-
          {{ is_state('binary_sensor.kjeller_garasjedor_contact', 'on') or
             is_state('binary_sensor.garasjeport_sensor', 'on') }}

### Template to see if there is any activity around the attic sensors ###
  - platform: template
    sensors:
      loft_aktivitet:
        friendly_name: "Loft Aktivitet"
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.loft_bevegelse_occupancy', 'on') or
             is_state('binary_sensor.loft_trappesensor_occupancy', 'on') }}


### Notify ###

notify:
  - name: 'Eirikz Telegram'
    platform: telegram
    chat_id: !secret eirikzchatid

  - name: 'W Telegram'
    platform: telegram
    chat_id: !secret wchatid

  - name: 'WE Telegram'
    platform: group
    services:
      - service: eirikz_telegram
      - service: w_telegram 





### Telegram Bot ###

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret eirikzchatid
      - !secret wchatid

### Climate ###

climate:
  - platform: climate_ip
    config_file: '/config/custom_components/climate_ip/samsung_2878.yaml'
    ip_address: !secret climateip
    token: !secret climatetoken
    mac: !secret climatemac
    name: 'Varmepumpe Stue'
    poll: True

  - platform: smartir
    name: 'Varmepumpe Soverom'
    unique_id: soverompumpe
    device_code: 1501
    controller_data: remote.broadlink_soverom_remote
    temperature_sensor: sensor.soverom_temperatur_temperature
    humidity_sensor: sensor.soverom_temperatur_humidity


### Adaptive lighting config ### 
adaptive_lighting:
- name: "primaergruppe"
  lights:
    - light.primaer_lys

  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

- name: "peis"
  lights:
    - light.peislys
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 20
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

- name: "do"
  lights:
    - light.do_taklys
    - light.do_hyllelampe
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 15
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true


- name: "kjeller"
  lights:
    - light.kjellergruppe
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

- name: "loft"
  lights:
    - light.loft_lys
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

- name: "kveldsgruppe"
  lights:
    - light.kveldsgruppe
#    - light.kjokken_bordlampe
  prefer_rgb_color: false
  transition: 45
#  only_once: true
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  detect_non_ha_changes: true
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true


- name: "kjokkenbenkelys"
  lights:
    - light.kjokkenbenk_under
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 20
  max_brightness: 70
  min_color_temp: 4000
  max_color_temp: 6000
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true

- name: "eirikkontor"
  lights:
    - light.eirikgruppe
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

- name: "kjokken"
  lights:
   - light.kjokkengrp
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true


### Pull home calendar into HA ###

calendar:
  - platform: caldav
    username: !secret caldavuser
    password: !secret caldavpass
    url: !secret caldavurl

### Importing Wrok Calendar ###

ics_calendar:
  calendars:
    - name: "EzCal"
      url: !secret ezhpecal

### Home connect alternative integration ###

home_connect_alt:
  client_id: !secret homeconnectaltclientid
  client_secret: !secret homeconnectaltclientsecret

### Manual Google Assitant integration becuase I have intention of using Nabu Casa ###

google_assistant:
  project_id: home-assistant-6f0bd
  service_account: !include SERVICE_ACCOUNT.json
  report_state: true
  expose_by_default: false
  exposed_domains:
    - switch
    - light
  entity_config:
    light.kjokkengrp:
      room: KJØKKEN
      aliases: kjøkkenlys
      name: kjøkkenlys

    light.utegruppe:
      room: UTE
      aliases: Utelys
      name: Utelys


