homeassistant:
  name: Home
  latitude: 60.108695
  longitude: 11.368363
  elevation: 220
  unit_system: metric
  time_zone: Europe/Oslo
  currency: NOK
  allowlist_external_dirs:
    - /tmp
  packages: !include_dir_named packages

##Define External\Internal URI##
  external_url: !secret baseurl
  internal_url: !secret baseurl


##Eirikz added MFA###
  auth_mfa_modules:
    - type: totp

  customize: !include customize.yaml

system_health:


energy:

#6## Enable blueprints ###
blueprint:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.11 

python_script:

conversation:

history:

logbook:

map:

sun:

### Input booleans ###

input_boolean: 
  dummy_fremme:
    name: "Dummy Fremme Input Boolean"
    icon: mdi:sticker-emoji
    initial: on

  dummy_bak:
    name: "Dummy Bak Input Boolean"
    icon: mdi:sticker-emoji
    initial: on


### Input Text ###

input_text:
  symfonisk_eirik_kontor:
    name: bahhumbug
    initial: text

  kjokken_lyd:
    name: kjokkenlyd
    initial: text



### Input Selects ####

input_select:
   loftlys:
     name: Loftlys
     options:
       - loftheltpa
       - loftheltav
     icon: mdi:lightbulb-on-outline

   eirik_status_dropdown:
     name: Eirik
     options:
       - Hjemme
       - Kom akkurat hjem
       - Dro akkurat ut
       - Ute
       - Bortreist
     initial: Hjemme

   w_status_dropdown:
     name: W
     options:
       - Hjemme
       - Kom akkurat hjem
       - Dro akkurat ut
       - Ute
       - Bortreist
     initial: Hjemme

   w_kontor:
     name: W Kontor Bryter
     options:
       - w_kontor_1
       - w_kontor_2
       - w_kontor_3
       - w_kontor_4
       - w_kontor_5
     initial: w_kontor_1

### Weather ###

weather:

### TTS ###

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    language: 'no'

### Includes

group: !include groups.yaml
automation: !include automations.yaml
automation mine: !include_dir_merge_list automation/
script: !include scripts.yaml
sensor: !include sensors.yaml


logger:
  default: warn
  logs:
   homeassistant.components.google_assistant.http: critical

 
### Telldus Live ###

tellduslive:
  host: !secret telldusip

### Lights ###
mqtt: 
  light:

### Zigbee2mqtt groups ###


    - schema: json
      name: KjellerGruppe
      command_topic: "zigbee2mqtt/kjellergruppe/set"
      state_topic: "zigbee2mqtt/kjellergruppe"

      color_temp: false
      brightness: true
      rgb: false

    - schema: json
      name: soveromgruppe
      command_topic: "zigbee2mqtt/soveromgruppe/set"
      state_topic: "zigbee2mqtt/soveromgruppe"

      color_temp: true
      brightness: true
      rgb: false

    - schema: json
      name: utegruppe
      command_topic: "zigbee2mqtt/utegruppe/set"
      state_topic: "zigbee2mqtt/utegruppe"

      color_temp: true
      brightness: true
      rgb: false

    - schema: json
      name: Kveldsgruppe
      command_topic: "zigbee2mqtt/kvelds_gruppe/set"
      state_topic: "zigbee2mqtt/kvelds_gruppe"

      color_temp: true
      brightness: true
      rgb: false



### Light Switches ###
light: 

  - platform: switch
    name: Stue Gangbord
    entity_id: switch.lys_gangbord

  - platform: switch
    name: Kjokken Stor Pære
    entity_id: switch.kjokken_stor_paere

### Light Groups ###

  - platform: group
    name: Alvakjokken
    entities:
      - light.alva_mikro
      - light.alva_komfyr
      - light.alva_benkelys

  - platform: group
    name: Soverom_lys
    entities:
      - light.soverom_hodegavel
      - light.eirik_soverom
      - light.soverom_lampe_w
  
  - platform: group
    name: W_kontor_lys_gruppe
    entities:
      - light.w_kontor_liten1
      - light.w_kontor_liten2
      - light.w_kontor_tak
      - light.w_kontor_spiss

  - platform: group
    name: Primær_lys
    entities:
      - light.stue_stuebord
      - light.stue_gul_gulvlampe

  - platform: group
    name: Kjeller_lys
    entities:
      - light.kjeller_ganglys_light
      - light.kjeller_vaskerom1_light
      - light.kjeller_vaskerom2_light
      - light.kjeller_vaskerom3_light
      - light.kjeller_trappelys_light
      - light.kjeller_fryserom_light
      - light.kjeller_bod_light

  - platform: group
    name: Loft_lys
    entities:
      - light.loft_taklys_1
      - light.loft_taklys_2
      - light.loft_gulvlampe1
      - light.loft_gulvlampe2
      - light.loft_gulvlampe3
      - light.loft_trappelys

  - platform: group
    name: Do_lys
    entities:
      - light.do_hyllelampe
      - light.do_taklys

  - platform: group
    name: garasjegruppe
    entities:
      - light.garasjelys1

### Yeelight ###

yeelight:
  devices:
    192.168.1.81:
      name: "Loft Taklys 1"
      model: color2
    192.168.1.82:
      name: "Loft Taklys 2"
      model: color2
    192.168.1.83:
      name: "Soverom Hodegavel"
      model: strip1

### Switches ###

switch:

### Switch Templates ###

  - platform: template
    switches:
      garasjedor:
        value_template: "{{ is_state('binary_sensor.garasjeport_sensor', 'on') }}"
        turn_on:
          service: cover.open_cover
          data:
            entity_id: cover.garasjeport_cover
        turn_off:
          service: cover.close_cover
          data:
            entity_id: cover.garasjeport_cover
        icon_template: >-
          {% if is_state('cover.garasjeport_cover', 'open') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}


zone: !include zones.yaml 

scene: !include scenes.yaml


media_player:

### Broadlink devices ###
  - platform: smartir
    name: LoftTV
    unique_id: lofttv
    device_code: 1060
    controller_data: remote.broadlink_loft_remote

  - platform: smartir
    name: LoftForsterker
    unique_id: loftforsterker
    device_code: 1121
    controller_data: remote.broadlink_loft_remote


### WoL ###

wake_on_lan:


### YAML mode for Lovelace ###

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/calendar-card/calendar-card.js
      type: js
    - url: /hacsfiles/light-entity-row/light-entity-row.js
      type: js
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/spotify-card/spotify-card.js
      type: module
    - url: /hacsfiles/seventeen-track-card/seventeen-track-card.js
      type: js
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/surveillance-card/surveillance-card.js
      type: module
    - url: /hacsfiles/travel-time-card/travel-time-card.js
      type: js
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: js 
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: js
    - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
      type: js
    - type: js
      url: /hacsfiles/lovelace-valetudo-map-card/valetudo-map-card.js
    - url: https://cdn.jsdelivr.net/gh/bramkragten/weather-card/dist/weather-card.min.js
      type: module

### Binary sensors ###

binary_sensor:

### Template for both basement doors open \ close will trigger lights in basement ###

  - platform: template
    sensors:
      kjeller_apen:
        friendly_name: "Kjellerdører åpne"
        device_class: door
        value_template: >-
          {{ is_state('binary_sensor.kjeller_trappedor_contact', 'on') or
             is_state('binary_sensor.kjeller_garasjedor_contact', 'on') }}

  - platform: template
    sensors:
      garasje_apen:
        friendly_name: "Garasjen er entret"
        device_class: door
        value_template: >-
          {{ is_state('binary_sensor.kjeller_garasjedor_contact', 'on') or
             is_state('binary_sensor.garasjeport_sensor', 'on') }}

  - platform: template
    sensors:
      loft_aktivitet:
        friendly_name: "Loft Aktivitet"
        device_class: motion
        value_template: >-
          {{ is_state('binary_sensor.loft_bevegelse_occupancy', 'on') or
             is_state('binary_sensor.loft_trappesensor_occupancy', 'on') }}

  - platform: template
    sensors:
      e_og_w_lys:
        friendly_name: "Kontorlys oppe"
        device_class: motion
        value_template: >-
          {{ is_state('light.eirik_kontor_lys', 'on') or
             is_state('light.w_kontor_lys_gruppe', 'on') }}


### Notify ###

notify:
  - name: 'Eirikz Telegram'
    platform: telegram
    chat_id: !secret eirikzchatid

  - name: 'W Telegram'
    platform: telegram
    chat_id: !secret wchatid

  - name: 'WE Telegram'
    platform: group
    services:
      - service: eirikz_telegram
      - service: w_telegram 


### MariaDB instead of SQLite ###

recorder:
  db_url: !secret mariadb

### Persons ###

person:

### Telegram Bot ###

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret eirikzchatid
      - !secret wchatid

### Climate ###

climate:
  - platform: climate_ip
    config_file: '/config/custom_components/climate_ip/samsung_2878.yaml'
    ip_address: !secret climateip
    token: !secret climatetoken
    mac: !secret climatemac
    name: 'Varmepumpe Stue'
    poll: True

  - platform: smartir
    name: 'Varmepumpe Soverom'
    unique_id: soverompumpe
    device_code: 1501
    controller_data: remote.broadlink_soverom_remote
    temperature_sensor: sensor.soverom_temperatur_temperature
    humidity_sensor: sensor.soverom_temperatur_humidity


### Webhooks ###

webhook:

### SmartIR ###

smartir:


### Microsoft Graph ###
microsoft_graph:
  client_id: !secret mgclientid 
  client_secret: !secret mgclientsecret 


adaptive_lighting:
- name: "primaergruppe"
  lights:
    - light.primaer_lys

  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

- name: "peis"
  lights:
    - light.peislys
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 20
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

- name: "do"
  lights:
    - light.do_taklys
    - light.do_hyllelampe
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 15
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true


- name: "kjeller"
  lights:
    - light.kjellergruppe
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

- name: "loft"
  lights:
    - light.loft_lys
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

- name: "kveldsgruppe"
  lights:
    - light.kveldsgruppe
#    - light.kjokken_bordlampe
  prefer_rgb_color: false
  transition: 45
#  only_once: true
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  detect_non_ha_changes: true
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true


- name: "kjokkenbenkelys"
  lights:
    - light.kjokkenbenk_under
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 20
  max_brightness: 70
  min_color_temp: 4000
  max_color_temp: 6000
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true

- name: "eirikkontor"
  lights:
    - light.eirikgruppe
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 1
  max_brightness: 50
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true

utility_meter:

### Volvo XC90 ###

volvooncall:
  username: !secret volvouser
  password: !secret volvopass
  mutable: true


powercalc:
