homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 60.108695
  longitude: 11.368363
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 220
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  whitelist_external_dirs:
    - /tmp
#  customize: !include customize.yaml
  packages: !include_dir_named packages

##Eirikz added MFA###
  auth_mfa_modules:
    - type: totp

  customize: !include customize.yaml

system_health:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
 http:
    base_url: !secret baseurl
    ssl_certificate: /config/certificate.pem
    ssl_key: /config/privkey.pem
    api_password: !secret apipassword

updater:
  include_used_components: true

python_script:

conversation:

history:

logbook:

map:

sun:

### Input booleans ###

input_boolean: 
  dummy_fremme:
    name: "Dummy Fremme Input Boolean"
    icon: mdi:sticker-emoji
    initial: on

### Input Selects ###

input_select:
   loftlys:
     name: Loftlys
     options:
       - loftheltpa
       - loftheltav
     icon: mdi:lightbulb-on-outline

   eirik_status_dropdown:
     name: Eirik
     options:
       - Hjemme
       - Kom akkurat hjem
       - Dro akkurat ut
       - Ute
       - Bortreist
     initial: Hjemme

   w_status_dropdown:
     name: W
     options:
       - Hjemme
       - Kom akkurat hjem
       - Dro akkurat ut
       - Ute
       - Bortreist
     initial: Hjemme

### Weather ###

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

### TTS ###

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    base_url: !secret baseurl_ga
    language: 'no'


cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml


logger:
  default: warn
  logs:
   homeassistant.components.ps4.media_player: error 
   hacs: debug

### Xiaomi Gateway ###

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomimac
      key: !secret xiaomigw
      host: !secret xiaomiip
 
### Telldus Live ###

tellduslive:
  host: !secret telldusip

### Device Trackers ###

device_tracker:

  - platform: ping
    consider_home: 180
    hosts:
      werofon: !secret werofon
      eirikfon: !secret eirikfon


### Lights ###

light:


### Zigbee2mqtt groups ###

  - platform: mqtt
    schema: json
    name: StueGruppe
    command_topic: "zigbee2mqtt/stuegruppe/set"
    state_topic: "zigbee2mqtt/stuegruppe"

    color_temp: true
    brightness: true
    rgb: false

  - platform: mqtt
    schema: json
    name: KjøkkenGruppe
    command_topic: "zigbee2mqtt/kjokkengruppe/set"
    state_topic: "zigbee2mqtt/kjokkengruppe"

    color_temp: true
    brightness: true
    rgb: false


  - platform: mqtt
    schema: json
    name: KjellerGruppe
    command_topic: "zigbee2mqtt/kjellergruppe/set"
    state_topic: "zigbee2mqtt/kjellergruppe"

    color_temp: false
    brightness: true
    rgb: false


  - platform: mqtt
    schema: json
    name: eirikgruppe
    command_topic: "zigbee2mqtt/eirikgruppe/set"
    state_topic: "zigbee2mqtt/eirikgruppe"

    color_temp: false
    brightness: true
    rgb: false

  - platform: mqtt
    schema: json
    name: soveromgruppe
    command_topic: "zigbee2mqtt/soveromgruppe/set"
    state_topic: "zigbee2mqtt/soveromgruppe"

    color_temp: true
    brightness: true
    rgb: false

  - platform: mqtt
    schema: json
    name: utegruppe
    command_topic: "zigbee2mqtt/utegruppe/set"
    state_topic: "zigbee2mqtt/utegruppe"

    color_temp: true
    brightness: true
    rgb: false


### Mi-Light ###

  - platform: limitlessled
    bridges:
      - host: !secret limitlessip
        groups:
        - number: 1
          name: Bokhylle

### Light Switches ###

  - platform: switch
    name: Stue Gangbord
    entity_id: switch.lys_gangbord

  - platform: switch
    name: dim
    entity_id: switch.dim

  - platform: switch
    name: Stue Stålampe
    entity_id: switch.stalampe

### Light Groups ###

  - platform: group
    name: Stue_lys
    entities:
      - light.stue_stuebord_light
      - light.stue_yttergang_vegglys
      - light.stue_vinduslampe1_light
      - light.stue_vinduslampe2_light
      - light.stue_gulvlampe1_light
      - light.stue_gulvlampe2_light
      - light.stue_gulvlampe3_light
      - light.stue_bikkjelampe_light
      - light.stue_lys_bak_tv_light
      - light.stue_stort_vitrineskap_light
      - light.stue_lite_vitrineskap
      - light.stue_lyst_vitrineskap
      - light.stue_peislys
      - light.stue_mellomgang_light
      - light.stue_yttergang_tak_light

  - platform: group
    name: Kjokken_lys
    entities:
      - light.kjokken_benkelys_light
      - light.kjokken_vinduslampe_light
      - light.kjokken_bordlampe_light
      - light.kjokken_benke_underlys_light
      - light.kjokken_taklampe_light
      - light.kjokken_ventilator_light


  - platform: group
    name: Kjeller_lys
    entities:
      - light.kjeller_ganglys_light
      - light.kjeller_vaskerom1_light
      - light.kjeller_vaskerom2_light
      - light.kjeller_vaskerom3_light
      - light.kjeller_trappelys_light
      - light.kjeller_fryserom_light
      - light.kjeller_bod_light

  - platform: group
    name: Loft_lys
    entities:
      - light.loft_taklys_1
      - light.loft_taklys_2
      - light.gulvlampe_loft_1
      - light.gulvlampe_loft_2
      - light.gulvlampe_loft_3

  - platform: group
    name: Kontor_eirik_lys
    entities:
      - light.eirik_kontor_light1
      - light.eirik_kontor_light2
      - light.eirik_kontor_light3


  - platform: group
    name: Do_lys
    entities:
      - light.do_hyllelampe_light
      - light.do_vegglampe_light

  - platform: group
    name: halloween
    entities:
      - light.grin
      - light.smile

### Yeelight ###

yeelight:
  devices:
    192.168.1.81:
      name: "Loft Taklys 1"
      model: color2
    192.168.1.82:
      name: "Loft Taklys 2"
      model: color2
    192.168.1.83:
      name: "Soverom Hodegavel"
      model: strip1

### Switches ###

switch:

  - platform: broadlink
    host: 192.168.1.70
    mac: 'c8:f7:42:75:0a:28'
    type: rm_mini

### Switch Templates ###

  - platform: template
    switches:
      garasjedor:
        value_template: "{{ is_state('binary_sensor.garasjeport_sensor', 'on') }}"
        turn_on:
          service: cover.open_cover
          data:
            entity_id: cover.garasjeport_cover
        turn_off:
          service: cover.close_cover
          data:
            entity_id: cover.garasjeport_cover
        icon_template: >-
          {% if is_state('cover.garasjeport_cover', 'open') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}


### Circadian Lighting ###

  - platform: circadian_lighting
    name: stue
    lights_brightness:
      - light.stuegruppe
    max_brightness: 75
    min_brightness: 1

    lights_ct:
      - light.stuegruppe

  - platform: circadian_lighting
    name: peis
    lights_brightness:
      - light.stue_peislys
    max_brightness: 75
    min_brightness: 12

    lights_ct:
      - light.stue_peislys 

  - platform: circadian_lighting
    name: do
    lights_brightness:
      - light.do_vegglampe_light
      - light.do_hyllelampe_light
    max_brightness: 35
    min_brightness: 1

    lights_ct:
      - light.do_vegglampe_light
      - light.do_hyllelampe_light



  - platform: circadian_lighting
    name: kjeller
    lights_brightness:
      - light.kjeller_ganglys_light
      - light.kjeller_vaskerom1_light
      - light.kjeller_vaskerom2_light
      - light.kjeller_vaskerom3_light
      - light.kjeller_trappelys_light
      - light.kjeller_fryserom_light
      - light.kjeller_bod_light
#      - light.kjeller
    max_brightness: 75
    min_brightness: 1

  - platform: circadian_lighting
    name: loft
    lights_brightness:
      - light.loft
    max_brightness: 75
    min_brightness: 1

    lights_ct:
      - light.loft_taklys_1
      - light.loft_taklys_2

  - platform: circadian_lighting
    name: kjokken   
    lights_brightness:
      - light.kjokkengruppe
    max_brightness: 75
    min_brightness: 1


  - platform: circadian_lighting
    name: kontor
    lights_brightness:
      - light.kontor_eirik_lys
    max_brightness: 75
    min_brightness: 1


zone: !include zones.yaml 

scene: !include scenes.yaml

### Spotify ###

spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_clientsecret

### WebosTV ###

webostv:
  host: 192.168.1.32
  name: StueTV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "14-C9-13-15-1F-BD"
      broadcast_address: 192.168.1.255

### Media Player Platform ###

media_player:

### Roku ###

  - platform: roku
    scan_interval: 10

### Onkyo ###

  - platform: onkyo
    host: !secret onkyoip
    name: Stueforsterker

### WoL ###

wake_on_lan:

### Roborock ###

vacuum:
  - platform: xiaomi_miio
    host: !secret roborockip
    token: !secret vacuum

### Google Calendar ###

google:
  client_id: !secret google_clientid
  client_secret: !secret google_clientsecret

### Circadian Lighting ###

circadian_lighting:
  interval: 600
  transition: 60
  min_colortemp: 2200

### YAML mode for Lovelace ###

lovelace:
  mode: yaml
  resources:
    - url: /community_plugin/calendar-card/calendar-card.js
      type: js
    - url: /local/monster-card.js?v=1
      type: js
    - url: /community_plugin/light-entity-row/light-entity-row.js
      type: js
    - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /community_plugin/spotify-card/spotify-card.js
      type: module
    - url: /community_plugin/seventeen-track-card/seventeen-track-card.js
      type: js
    - url: /community_plugin/simple-thermostat/simple-thermostat.js
      type: module
    - url: /community_plugin/surveillance-card/surveillance-card.js
      type: module
    - url: /community_plugin/travel-time-card/travel-time-card.js
      type: js
    - url: /community_plugin/lovelace-card-mod/card-mod.js
      type: js 
    - url: /community_plugin/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /community_plugin/compact-custom-header/compact-custom-header.js
      type: module
    - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /community_plugin/lovelace-card-tools/card-tools.js
      type: module
    - url: /community_plugin/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
      type: module 
    - url: /community_plugin/upcoming-media-card/upcoming-media-card.js
      type: js


### Binary sensors ###

binary_sensor:
  - platform: ping
    host: 192.168.1.36
    name: Temari
    count: 3
    scan_interval: 30

  - platform: ping
    host: 192.168.1.40
    name: Kakuzu
    count: 3
    scan_interval: 30

  - platform: mqtt
    name: "fremme"
    state_topic: "cameras/fremme/motion"

  - platform: mqtt
    name: "bak"
    state_topic: "cameras/bak/motion"



### Template for both basement doors open \ close will trigger lights in basement ###

  - platform: template
    sensors:
      kjeller_apen:
        friendly_name: "Kjellerdører åpne"
        device_class: door
        value_template: >-
          {{ is_state('binary_sensor.kjeller_trapp', 'on') or
             is_state('binary_sensor.kjeller_garasjedor', 'on') }}


### Notify ###

notify:
  - name: 'Eirikz Telegram'
    platform: telegram
    chat_id: !secret eirikzchatid

  - name: 'W Telegram'
    platform: telegram
    chat_id: !secret wchatid

  - name: 'WE Telegram'
    platform: group
    services:
      - service: eirikz_telegram
      - service: w_telegram 


### MariaDB instead of SQLite ###

recorder:
  db_url: !secret mariadb

### Persons ###

person:

### Telegram Bot ###

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret eirikzchatid
      - !secret wchatid

### Climate ###

climate:
  - platform: climate_ip
    config_file: '/home/hass/homeassistant/custom_components/climate_ip/samsung_2878.yaml'
    ip_address: !secret climateip
    token: !secret climatetoken
    mac: !secret climatemac
    name: 'Varmepumpe Stue'
    poll: True

  - platform: smartir
    name: 'Varmepumpe Loft'
    unique_id: loftpumpe
    device_code: 1260
    controller_data: 192.168.1.70
    temperature_sensor: sensor.0x00158d000272cf43_temperature
    humidity_sensor: sensor.0x00158d000272cf43_humidity


### InfluxDB ###

influxdb:
  host: 192.168.1.40
  port: 8086
  username: !secret influxdbuser
  password: !secret influxdbpass
  ssl: false
  verify_ssl: false


### Image Processing ###

image_processing:
  - platform: doods
    scan_interval: 10000
    url: "http://192.168.1.40:8011"
    detector: tensorflow
    source:
      - entity_id: camera.fremme
      - entity_id: camera.bak
    file_out:
      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    confidence: 20
    labels:
      - person
      - car
      - cat

### ffmpeg ###

ffmpeg:

### Stream ###

stream:

### LIFE360 ###

life360:
  accounts:
    - username: !secret LIFE360_USERNAME
      password: !secret LIFE360_PASSWORD
  driving_speed: 15
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  warning_threshold: 2
  error_threshold: 3


### WWLLN ###

wwlln:
  radius: 50


### MQTT ###

mqtt:
  discovery: true
  broker: 192.168.1.40
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


### Zigbee2mqtt network map ###

webhook:
 
zigbee2mqtt_networkmap:


### Sonos ####

sonos:
  media_player:
    hosts:
      - !secret sonoskontorip

### Google Cast ###

cast:
  media_player:
    - host: !secret kjokkenhubip
    - host: !secret wkontorip


### MJPEG camera from Motion ###

camera:
  - platform: generic
    name: Fremme
    stream_source: rtsp://192.168.1.63/stream1
    still_image_url: http://192.168.1.40:20100/picture/1/current/
    username: admin
    password: admin


  - platform: generic
    name: Bak
    stream_source: rtsp://192.168.1.62/stream1
    still_image_url: http://192.168.1.40:20100/picture/2/current/
    username: admin
    password: admin

### Siemens HomeConnect ###

homeconnect:
  client_id: !secret HC_clientID
  client_secret: !secret HC_clientS

### SmartIR ###

smartir:

### Mobile App ###

mobile_app:
