views:
  - !include /config/ui-lovelace/001-eirik.yaml
  - !include /config/ui-lovelace/002-w.yaml
  - !include /config/ui-lovelace/010-temp.yaml
  - !include /config/ui-lovelace/011-temp.yaml
  - !include /config/ui-lovelace/020-media.yaml
  - !include /config/ui-lovelace/030-eirikz.yaml
  - !include /config/ui-lovelace/031-eirikz.yaml
  - !include /config/ui-lovelace/040-stovsuger.yaml
  - !include /config/ui-lovelace/050-lys.yaml
  - !include /config/ui-lovelace/051-lys.yaml
  - !include /config/ui-lovelace/060-kamera.yaml
  - !include /config/ui-lovelace/061-kamera.yaml
  - !include /config/ui-lovelace/070-kalender.yaml
  - !include /config/ui-lovelace/080-brytereogautomasjoner.yaml
  - !include /config/ui-lovelace/090-multimedia.yaml
  - !include /config/ui-lovelace/100-wakeup.yaml
  - !include /config/ui-lovelace/110-pakker.yaml
  - !include /config/ui-lovelace/120-strom.yaml
  - !include /config/ui-lovelace/121-strom.yaml
  - !include /config/ui-lovelace/130-drivhus.yaml
  - !include /config/ui-lovelace/140-soppel.yaml
  - !include /config/ui-lovelace/150-z2m.yaml
