resources:
  - url: 'https://unpkg.com/moment@2.22.2/moment.js'
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
    type: js
  - url: /local/monster-card.js?v=1
    type: js
  - url: /local/vertical-stack-in-card.js?v=1
    type: js
  - url: '/local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=1.4.9'
    type: module
  - url: 'https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.3/dist/spotify-card.umd.js'
    type: module
  - url: '/local/seventeen-track-card.js?v=1.0'
    type: js
  - url: /local/community/surveillance-card/surveillance-card.js
    type: module
  - url: /local/mini-media-player-bundle.js?v=1.1.3
    type: module
  - url: /local/simple-thermostat.js?v=1
    type: module
  - url: /local/card-modder.js?v=1
    type: js
  - url: /local/auto-entities.js?v=1
    type: js
  - url: /local/card-tools.js?v=1
    type: js
  - url: /local/community/travel-time-card/travel-time-card.js
    type: js

cch:
  menu: clock
  notifications: hide
  clock_format: 24
  swipe: true


views:
  - !include /config/ui-lovelace/001-eirik.yaml
  - !include /config/ui-lovelace/002-w.yaml
  - !include /config/ui-lovelace/010-temp.yaml
  - !include /config/ui-lovelace/011-temp.yaml
  - !include /config/ui-lovelace/020-media.yaml
  - !include /config/ui-lovelace/030-eirikz.yaml
  - !include /config/ui-lovelace/031-eirikz.yaml
  - !include /config/ui-lovelace/040-stovsuger.yaml
  - !include /config/ui-lovelace/050-lys.yaml
  - !include /config/ui-lovelace/051-lys.yaml
  - !include /config/ui-lovelace/060-kamera.yaml
  - !include /config/ui-lovelace/061-kamera.yaml
  - !include /config/ui-lovelace/070-kalender.yaml
  - !include /config/ui-lovelace/080-brytereogautomasjoner.yaml
  - !include /config/ui-lovelace/090-multimedia.yaml
  - !include /config/ui-lovelace/100-wakeup.yaml
  - !include /config/ui-lovelace/110-pakker.yaml
  - !include /config/ui-lovelace/120-strom.yaml
  - !include /config/ui-lovelace/121-strom.yaml
  - !include /config/ui-lovelace/130-drivhus.yaml
