#resources:
#  - url: /hacsfiles/calendar-card/calendar-card.js
#    type: js
#  - url: /local/monster-card.js?v=1
#    type: js
#  - url: /hacsfiles/light-entity-row/light-entity-row.js
#    type: 
#  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
#    type: module
#  - url: /hacsfiles/spotify-card/spotify-card.js
#    type: module
#  - url: /hacsfiles/seventeen-track-card/seventeen-track-card.js
#    type: js
#  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
#    type: module
#  - url: /hacsfiles/surveillance-card/surveillance-card.js
#    type: module
#  - url: /hacsfiles/travel-time-card/travel-time-card.js
#    type: js
#  - url: /hacsfiles/lovelace-card-mod/card-mod.js
#    type: js 
#  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
#    type: module
#  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
#    type: js
#  - url: /hacsfiles/compact-custom-header/compact-custom-header.js
#    type: module
#  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
#    type: module
#  - url: /hacsfiles/lovelace-card-tools/card-tools.js
#    type: module
#  - url: /hacsfiles/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
#    type: module 
#  - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
#    type: js
#cch:
 # menu: clock
 # notifications: hide
 # clock_format: 24
 # swipe: true


views:
  - !include /home/homeassistant/homeassistant/ui-lovelace/001-eirik.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/002-w.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/010-temp.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/011-temp.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/020-media.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/030-eirikz.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/031-eirikz.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/040-stovsuger.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/050-lys.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/051-lys.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/060-kamera.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/061-kamera.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/070-kalender.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/080-brytereogautomasjoner.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/090-multimedia.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/100-wakeup.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/110-pakker.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/120-strom.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/121-strom.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/130-drivhus.yaml
  - !include /home/homeassistant/homeassistant/ui-lovelace/140-soppel.yaml
