resources:
  - url: 'https://unpkg.com/moment@2.22.2/moment.js'
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
    type: js
  - url: /local/monster-card.js?v=1
    type: js
  - url: /local/vertical-stack-in-card.js?v=1
    type: js
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
    type: module
  - url: 'https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.3/dist/spotify-card.umd.js'
    type: module
  - url: '/local/seventeen-track-card.js?v=1.0'
    type: js
  - url: /community_plugin/surveillance-card/surveillance-card.js
    type: module
  - url: /local/mini-media-player-bundle.js?v=1.1.3
    type: module
  - url: /local/simple-thermostat.js?v=1
    type: module
  - url: /local/card-modder.js?v=1
    type: js
  - url: /local/auto-entities.js?v=1
    type: js
  - url: /local/card-tools.js?v=1
    type: js

views:
  - path: default_view
    title: Temp
    icon: 'mdi:temperature-celsius'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
            main_config: true
            menu: clock
            notifications: hide
            clock_format: 24
            swipe: true
            exceptions:
              - conditions:
                  user: eirikz
                config:
                  hide_tabs: 3,4,5
          - type: vertical-stack
            cards:
             - type: weather-forecast
               entity: weather.dark_sky
             - type: custom:simple-thermostat
               entity: climate.varmepumpe_stue
               step_size: 1

  - path: media
    title: Media
    icon: 'mdi:music'
    panel: true
    cards:
      - type: vertical-stack
        cards: 
          - type: custom:compact-custom-header
          - type: horizontal-stack
            cards:
              - entity: media_player.spotify
                type: custom:mini-media-player
                info: short
                artwork: cover
                hide:
                  mute: true
                  icon: true
                  power: true

              - entity: media_player.kontormini
                type: custom:mini-media-player
                info: short
                artwork: cover
                hide:
                  mute: true
                  icon: true
                  power_state: false
          - type: horizontal-stack
            cards:
              - entity: media_player.stueforsterker
                type: custom:mini-media-player
                info: short
                artwork: cover
                hide:
                  mute: true
                  icon: true
                  power_state: false

  - path: eirik
    title: Eirik
    icon: 'mdi:briefcase'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
          - type: glance
            title: Eirik
            entities:
              - entity: sensor.eirik_til_hjem
                name: Tid Eirik bruker hjem
              - entity: sensor.hjemmefra_til_jobb
                name: Tid Eirik bruker til jobb
              - entity: sensor.eirik_batteri
                name: Eirik batterinivå
              - entity: sensor.eirik_motion
                name: Eirik i bevegelse
          - type: map
            default_zoom: 8
            aspect_ratio: 16:9
            entities:
              - device_tracker.eirik_mobil
              - zone.hjemme
              - zone.FBU

  - path: stovsuger
    title: støvsuger
    icon: 'mdi:robot-vacuum'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                cards:
                  - type: custom:compact-custom-header
                  - type: entity-button
                    entity: script.tomme
                    icon: mdi:bitbucket
                    color: auto
                    name: Tømme
                    tap_action:
                      action: toggle
                  - type: entity-button
                    entity: script.stovsug_tvstue
                    icon: mdi:sofa
                    color: auto
                    name: Stue
                  - type: entity-button
                    entity: script.stovsug_kjokken
                    icon: mdi:stove
                    color: auto
                    name: Kjøkken
              - type: horizontal-stack
                cards:
                  - type: entity-button
                    entity: script.stovsug_spisestue
                    icon: mdi:silverware-fork-knife
                    color: auto
                    name: Spisestue
                  - type: entity-button
                    entity: script.stovsug_huset
                    icon: mdi:home-circle
                    color: auto
                    name: Hele huset
                  - type: entity-button
                    entity: script.stovsug_barnerom
                    icon: mdi:baby
                    color: auto
                    name: Barnerom
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: glance
                    columns: 2
                    show_name: true
                    entities:
                      - entity: sensor.vacuum_cleaned_area
                      - entity: sensor.vacuum_cleaning_time
                  - type: glance
                    columns: 4
                    show_name: true
                    entities:
                      - entity: sensor.vacuum_cleanmainbrush
                      - entity: sensor.vacuum_cleansidebrush
                      - entity: sensor.vacuum_cleanfilter
                      - entity: sensor.vacuum_sensordirtyleft



  - path: Lys
    title: Lys
    icon: 'mdi:lightbulb'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.kjokken
                name: Kjøkken
              - type: light
                entity: light.stue
                name: Stue
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.kontor
                name: Kontor
              - type: light
                entity: light.soverom
                name: Soverom
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.loft
                name: Loft
              - type: light
                entity: light.kjeller
                name: Kjeller
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.nattlys
                name: Nattlys

  - path: Kamera
    title: Kamera
    icon: 'mdi:cctv'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
          - type: custom:surveillance-card
            thumb_interval: 15
            update_interval: 2
            cameras:
              - entity: camera.fremme
              - entity: camera.bak
        
  - path: Kalender
    title: Kalender
    icon: 'mdi:calendar'
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
          - entities:
              - calendar.eirikzhassgmailcom
              - calendar.calendar
            cards: null
            type: 'custom:calendar-card'

  - path: SwAndAut
    title: Brytere og Automasjoner
    icon: 'mdi:toggle-switch'
    show_header_toggle: true
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:auto-entities
            card:
              type: entites
            filter:
              include:
                - domain: automation
          - type: custom:auto-entities
            card:
              type: entities
            filter:
              include:
                - domain: switch

  - path: Multimedia
    title: Multimedia
    icon: 'mdi:video-vintage'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
          - type: horizontal-stack
            cards:
              - type: gauge
                unit: 'kBps'
                entity: sensor.qbittorrent_up_speed

              - type: gauge
                unit: 'kBps'
                entity: sensor.qbittorrent_down_speed

              - type: gauge
                entity: sensor.tautulli

  - path: Wakeup
    title: Multimedia
    icon: 'mdi:weather-sunset'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
          - type: entities
            entities:
              - automation.wakeup_light_soverom
              - input_boolean.wakeup

          - type: entities
            entities:
              - input_datetime.wakeup_time

  - path: Pakker
    title: Pakker
    icon: 'mdi:package-variant-closed'
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
          - type: custom:seventeen-track-card
            entity: sensor.seventeentrack_packages_in_transit

  - path: strom
    title: Strøm
    icon: 'mdi:power'
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
          - type: horizontal-stack
            cards:
              - type: picture-elements
                title: Varmtvannsbereder
                image: '/local/varmtvannsbereder.jpg'
                style:
                  width: 50%
                  height: 50%
                elements:
                  - type: state-label
                    entity: sensor.vvb_navarende_forbruk
                    prefix: "Nåværende Forbruk"
                    style:
                      top: 20%
                      right: 1%
                      color: rgb(0, 0, 0)
                      transform: translate(0%,-50%)
                      pointer-events: none
                      font-family: Trebuchet MS
                      font-size: 90%
                      font-weight: bold
                      border-color: rgb(34, 154, 210)
                      background-color: '#3090C7'
                      border-radius: 6px

                  - type: state-label
                    entity: sensor.vvb_dagens_forbruk
                    prefix: "Daglig Forbruk"
                    style:
                      top: 48%
                      right: 1%
                      color: rgb(0, 0, 0)
                      transform: translate(0%,-50%)
                      pointer-events: none
                      font-family: Trebuchet MS
                      font-size: 90%
                      font-weight: bold
                      border-color: rgb(34, 154, 210)
                      background-color: '#3090C7'
                      border-radius: 6px

                  - type: state-label
                    entity: sensor.vvb_manedlig_forbruk
                    prefix: "Månedlig Forbruk: "
                    style:
                      top: 74%
                      right: 1%
                      color: rgb(0, 0, 0)
                      transform: translate(0%,-50%)
                      pointer-events: none
                      font-family: Trebuchet MS
                      font-size: 90%
                      font-weight: bold
                      border-color: rgb(34, 154, 210)
                      background-color: '#3090C7'
                      border-radius: 6px

              - type: picture-elements
                title: Tørketrommel
                image: '/local/torketrommel.webp'
                style:
                  width: 50%
                  height: 50%
                elements:
                  - type: state-label
                    entity: sensor.torketrommel_manedlig
                    prefix: "Månedlig Forbruk: "
                    style:
                      top: 80%
                      right: 1%
                      color: rgb(0, 0, 0)
                      transform: translate(0%,-50%)
                      pointer-events: none
                      font-family: Trebuchet MS
                      font-size: 90%
                      font-weight: bold
                      border-color: rgb(34, 154, 210)
                      background-color: '#3090C7'
                      border-radius: 6px

                  - type: state-label
                    entity: sensor.torketrommel_daglig
                    prefix: "Daglig Forbruk: "
                    style:
                      top: 50%
                      right: 1%
                      color: rgb(0, 0, 0)
                      transform: translate(0%,-50%)
                      pointer-events: none
                      font-family: Trebuchet MS
                      font-size: 90%
                      font-weight: bold
                      border-color: rgb(34, 154, 210)
                      background-color: '#3090C7'
                      border-radius: 6px

                  - type: state-label
                    entity: sensor.torketrommel_power_2
                    prefix: "Nåværende Forbruk: "
                    style:
                      top: 20%
                      right: 1%
                      color: rgb(0, 0, 0)
                      transform: translate(0%,-50%)
                      pointer-events: none
                      font-family: Trebuchet MS
                      font-size: 90%
                      font-weight: bold
                      border-color: rgb(34, 154, 210)
                      background-color: '#3090C7'
                      border-radius: 6px

  - path: drivhus
    title: Drivhus
    icon: 'mdi:flower'
    cards:
      - type: vertical-stack
        cards:
          - type: custom:compact-custom-header
          - type: glance
            title: Temperaturer
            entities:
              - entity: sensor.temperature_drivhus
                name: Drivhus Aqara
              - entity: sensor.drivhusny_temperature
                name: Drivhus 433

